### ISSUE TITLE
Having issues with nested tabstop

### ISSUE THREAD

**Issue by PetitBandit** [quangnguyen30192/cmp-nvim-ultisnips#56]
```
snippet pT "Description" b
paddingTop: ${1:theme.spacing($2)},
endsnippet
```
Previously to the switch to cmp, i had this mapping that allowed to either replace completely $1 by typing or filling $2 by tabbing when on $1, this doesnt work anymore as I can t seem to tab to the next. 
Can someone helps please as this was very useful for me. 
Thanks !

**Comment by smjonas** [comment]
Thanks for reporting, this issue with select-mode mappings was bugging me for a while and I am glad you brought it up again! Please also read the [Known Issues](https://github.com/quangnguyen30192/cmp-nvim-ultisnips#known-issues) section in the readme since you need to set an UltiSnips variable.

Related: #5.
